name: Generate Keystore (run once)

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v -keystore niksamgenerators-release.jks \
            -alias niksamgenerators \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass NiksamGen@2026Secure \
            -keypass NiksamGen@2026Secure \
            -dname "CN=NiksamGenerators, OU=NiksamGenerators, O=NiksamGenerators, L=Tehran, S=Tehran, C=IR"

      - name: Upload Keystore
        uses: actions/upload-artifact@v4
        with:
          name: niksamgenerators-release-keystore
          path: niksamgenerators-release.jks
